app:
  spot_folder   : "./data/spot/"
  tags_folder   : "./data/tags/"  
  txt_path      : "./data/txt/"
  tmp_folder    : "./data/tmp/"
  chat_ids      : "./data/bot/chat_ids.txt"
  restart_collect : False
  limit : 10
  sleep_time: 600
trends:
  simulate: False
  sleep_time: 600
  test_sleep_time: 120
  count: 10
img:
  count_for_spot: 10