
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/src/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
      - .:/home/src/
    restart: on-failure:5


  nginx:
    container_name: nginx-dci
    hostname: daycolorbot
    restart: "no"
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:5005"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./data/www/
        target: /usr/share/nginx/html
    deploy:
      resources:
        limits:
          cpus: '0.1'
        reservations:
          cpus: '0.05'

  redis: 
    image: redislabs/redismod
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
        reservations:
          cpus: '0.5'

  flask:
    build: 
      dockerfile: docker/flask/Dockerfile
    container_name: flask-dci
    # networks:
    #   mynetwork:
    #     ipv4_address: 10.0.0.10
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - type: bind
        source: ./app/flask
        target: /app
      - type: bind
        source: ./data
        target: /data
      #- .:/code
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
        reservations:
          cpus: '0.2'


  bot:
    container_name: bot-dci
    restart: always
    build:
      context: .
      dockerfile: docker/bot/Dockerfile
    # networks:
    #   mynetwork:
    #     ipv4_address: 10.0.0.17      
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./app/bot
        target: /app
      - type: bind
        source: ./config.yml
        target: /app/config.yml
      - type: bind
        source: ./data
        target: /app/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
        reservations:
          cpus: '0.5'
    depends_on:
      - redis
      - flask

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/
      - /app/node_modules
      # - type: bind
      #   source: ./frontend
      #   target: /app
    ports:
      - "3000:3000"
    # networks:
    #   - app_network