version: '3.8'

services:
  colorbot:
    container_name: daycolorbot
    hostname: daycolorbot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./app/out
        target: /app/out
      - type: bind
        source: ./app/data
        target: /app/data

    ports:
     - "127.0.0.1:8080:80"
volumes:
  shared:
    external: true
  data:
    external: true