
services:
  colorbot:
    container_name: daycolorbot
    hostname: daycolorbot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./out
        target: /app/out
      - type: bind
        source: ./data
        target: /app/data

    ports:
     - "127.0.0.1:5050:50"