[supervisord]
user=root
nodaemon=true
logfile=out/supervisord.log
# logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:collector]
command=python day_color.py
stdout_logfile=out/supervisord.log
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0
autorestart=true
autostart=true
numproc=2
stopwaitsecs=3600
process_name=%(program_name)s_%(process_num)02d

[program:bot]
command=python main.py
stdout_logfile=out/supervisord.log
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0
autorestart=true
autostart=true
numproc=2
stopwaitsecs=3600
process_name=%(program_name)s_%(process_num)02d

[program:sender]
command=python sender.py
stdout_logfile=out/supervisord.log
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0
autorestart=true
autostart=true
numproc=2
stopwaitsecs=3600
process_name=%(program_name)s_%(process_num)02d